export const IMAGES5X5 = [

    // { id: 10, src: "A3" },
    // { id: 14, src: "E3" },
    // { id: 22, src: "C5" },
    // { id: 2, src: "C1" },
    // { id: 3, src: "D1" },
    // { id: 19, src: "E4" },
    // { id: 5, src: "A2" },
    // { id: 16, src: "B4" },
    // { id: 7, src: "C2" },
    // { id: 21, src: "B5" },
    // { id: 9, src: "E2" },
    // { id: 11, src: "B3" },
    // { id: 6, src: "B2" },
    // { id: 24, src: "E5" },
    // { id: 0, src: "A1" },
    // { id: 12, src: "C3" },
    // { id: 15, src: "A4" },
    // { id: 8, src: "D2" },
    // { id: 1, src: "B1" },
    // { id: 18, src: "D4" },
    // { id: 20, src: "A5" },
    // { id: 4, src: "E1" },
    // { id: 17, src: "C4" },
    // { id: 23, src: "D5" },
    // { id: 13, src: "D3" }

    { id: 0, src: "A1" },
    { id: 1, src: "B1" },
    { id: 2, src: "C1" },
    { id: 3, src: "D1" },
    { id: 4, src: "E1" },
    { id: 5, src: "A2" },
    { id: 6, src: "B2" },
    { id: 7, src: "C2" },
    { id: 8, src: "D2" },
    { id: 9, src: "E2" },
    { id: 10, src: "A3" },
    { id: 11, src: "B3" },
    { id: 12, src: "C3" },
    { id: 13, src: "D3" },
    { id: 14, src: "E3" },
    { id: 15, src: "A4" },
    { id: 16, src: "B4" },
    { id: 17, src: "C4" },
    { id: 18, src: "D4" },
    { id: 19, src: "E4" },
    { id: 20, src: "A5" },
    { id: 21, src: "B5" },
    { id: 22, src: "C5" },
    { id: 23, src: "D5" },
    { id: 24, src: "E5" }
]